name: Release

on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
